### ISSUE TITLE
SEO rating

### ISSUE THREAD

**Issue by Daver2910** [scottsweb/scott.ee#87]
Hi Scott, 
I was wondering while using nuxt in universal mode, does this allow all your wp posts to be indexed by Google? 

thanks

**Comment by scottsweb** [comment]
That should be fine but I haven't spent a great deal of time testing it. 

I actually use the `generate` mode to create a static version of my site which gets indexed perfectly (https://nuxtjs.org/guide#static-generated-pre-rendering-) by Google. This removes the need to find some decent node.js hosting and allows me to host it on GitHub pages.

In universal mode, the server should query the WordPress API and create cached pages from that. All of which Google should have no trouble indexing. This is worth a read: 

https://medium.com/vue-mastery/best-practices-for-nuxt-js-seo-32399c49b2e5

**Comment by Daver2910** [comment]
Thats exactly what I wanted to hear. I will be implementing your method on a nuxt build very soon.Thanks for the feedback!!

**Comment by scottsweb** [comment]
No problem, good luck with the project.
